export const endpoints = {
  login: "/auth-service/api/login/otp/",
  forgotPassword: "forgot-password/",
  verifyOtp: "/auth-service/api/login/auth_code/",
  verifyAuthCode: "/auth-service/api/login/access_token/",
  resetPassword: "reset-password/",
  profile: "/business-service/api/profile/details/",
  profileUpdate: "/business-service/api/profile/update/",
  profileCategory: "/business-service/api/profile/category/",
  product: "/business-service/api/product/",
  catalog: "/business-service/api/catalog/",
  productCategory: "/business-service/api/product/category/",
  campaign: "/campaign-service/campaign/",
  campaignVendor: "/campaign-service/campaign/vendor",
  portfolio: "/campaign-service/portfolio/", // "portfolio/",
  addPortfolio: "/campaign-service/portfolio",
  addPortfolioEntity: "/campaign-service/portfolio/addEntity", // "portfolio/addEntity",
  removePortfolioEntity: "/campaign-service/portfolio/removeEntity", // "portfolio/removeEntity", //
  portfolioCategory: "/campaign-service/portfolio-category", // "portfolio-category/active/", //
  portfolioService: "/campaign-service/service", // "service/", //
  portfolioProduct: "/campaign-service/product", // "product/", //
  service: "/business-service/api/service/",
  serviceType: "/business-service/api/service/type/",
  wallet: "wallet-cash",
  transactionHistory: "transaction-history",
  cardDetails: "card/details",
  coupons: "coupons",
  couponsValidate: "coupons/validate",
  paymentSplitup: "payment/split-up",
  addProduct: "/business-service/api/product/",
  deleteProduct: "/business-service/api/product/",
  createAssetsOld: "/asset-service/api/",
  createAssets: "/asset-service/api/create/asset/",
  deleteAssets: "/asset-service/api/list/delete/",
  businessProducts: "/business-service/api/product/",
  checklistLookup: "/campaign-service/lookup/get-all",
};
