enum ROUTE {
  AUTH = "Auth",
  OTP = "OTP",
  LOGIN = "Login",
  EMAILLOGIN = "Email Login",
  PHONELOGIN = "Phone Login",
  FORGOTPASSWORD = "Forgot Password",
  RESETPASSWORD = "Reset Password",
  APP = "App",
  TABS = "Tabs",
  HAMBURGER = "Hamburger",
  HOME = "Home",
  LANDING = "Landing",
  CONTACT = "Contact",
  CAMPAIGNS = "Campaigns",
  CAMPAIGN = "Campaign",
  PRODUCTS = "Products",
  PRODUCT = "Product",
  SERVICES = "Services",
  ADDSERVICES = "AddServices",
  CHANGEPASSWORD = "ChangePassword",
  PROFILE = "Profile",
  EDITPROFILE = "EditProfile",
  ADDPRODUCT = "AddProduct",
  MYWALLET = "MyWallet",
  PORTFOLIO = "Portfolio",
  ADDCAMPAIGNS = "AddCampaigns",
  ADDPORTFOLIO = "AddPortfolio",
  EDITPORTFOLIO = "EditPortfolio",
  PAYMENT = "Payment",
  COUPONS = "Coupons",
  OTPPayment = "OTPPayment",
}

export default ROUTE;
